[project]
name = "autorewardbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MakeMeFifi", email = "chrismikolajek2006@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "humancursor>=1.1.5",
    "pyfiglet>=1.0.4",
    "rich>=15.0.0",
    "selenium>=4.48.0",
]

[project.scripts]
autorewardbot = "autorewardbot:main"

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"
